### ISSUE TITLE
Ship a yum/dnf repo file and the GPG key

### ISSUE THREAD

**Issue by elyscape** [KryptCo/kryptco.github.io#2]
The [RPM Linux install instructions][install] are currently fairly manual:
```shellsession
$ gpg --keyserver=hkp://keyserver.ubuntu.com:80 --recv-keys "C4A05888A1C4FA02E1566F859F2A29A569653940"
$ gpg --export --armor C4A05888A1C4FA02E1566F859F2A29A569653940 > /tmp/kryptco.key
$ sudo rpm --import /tmp/kryptco.key
$ sudo yum-config-manager --add-repo https://kryptco.github.io/yum # non-fedora only
$ sudo yum config-manager --add-repo https://kryptco.github.io/yum # fedora only
$ sudo yum install kr -y
```
If you hosted a file containing your GPG public key, and also a file called something like `kryptco.repo` with the following contents:
```conf
[kryptco]
name=Krypt.co Repository
baseurl=https://kryptco.github.io/yum/
gpgkey=https://kryptco.github.io/pubkey.gpg
enabled=1
gpgcheck=1
```
Then the steps could be consolidated to:
```shellsession
$ sudo yum-config-manager --add-repo https://kryptco.github.io/yum/kryptco.repo # non-fedora only
$ sudo dnf config-manager --add-repo https://kryptco.github.io/yum/kryptco.repo # fedora only
$ sudo yum install kr -y
```

[install]: https://krypt.co/docs/start/installation.html#rpm-linux-redhat-centos-fedora

**Comment by elyscape** [comment]
Pinging @kcking.

**Comment by kcking** [comment]
Sorry for the delay in responding to this! Your method does look simpler, thanks for pointing it out. I'll look into hosting a repo file on https://krypt.co

**Comment by kcking** [comment]
We just deployed a `.repo` file to `https://krypt.co/repo/yum.repo` and updated the installation instructions. Let us know if you have any issues!

**Comment by elyscape** [comment]
Looks good, though ideally the repo file would be called something like `krypto.repo` instead of `yum.repo`, as `yum-config-manager --add-repo` and `dnf config-manager --add-repo` basically just download the file into `/etc/yum.repos.d` without renaming it.

**Comment by kcking** [comment]
Good point, will update that shortly
